### ISSUE TITLE
初回インポート時にタブにKirinUtilの項が表示されない

### ISSUE THREAD

**Issue by YusukeSaitoHolo** [mizutanikirin/KirinUtil#1]
初回インポート時、UnityEditorで依存パッケージ(ZXingなど)がインストールされていないことによるエラーに起因して、タブにKirinUtilが表示されません。

例えばですが、KirinUtil.Coreの形でiTweenのみ依存するものだけインポートし、
その他の依存パッケージを必要とするモジュールは後で追加できるようにするのがよいかと思われます。

環境
Editor : Unity2019.2.21f1, Unity2019.2.18f1
KirinUtil : 1.04

**Comment by mizutanikirin** [comment]
ありがとうございます。インポート方法検討してみます。

**Comment by mizutanikirin** [comment]
iTween以外の外部Asset/dllを必要とするMovieManager、QRManager、PrintManagerを初期状態でOFFにしてインポート時にエラーが発生しないよう修正しました。ver1.0.5で対応しています。

**Comment by YusukeSaitoHolo** [comment]
ありがとうございます！
こちらでも、下記の環境でiTween, KitrinUtilのインストール後にタブに表示されることを確認しました。

Unity : 2019.2.21f1
KirinUtil : 1.05
